# Generated by Django 5.2.7 on 2025-11-17 23:08

import colorfield.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdministrativeUnit",
            fields=[
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedDate"),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_column="ModifiedDate"),
                ),
                (
                    "administrative_unit_id",
                    models.AutoField(
                        db_column="AdministrativeUnitID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(
                        db_column="ReferenceCode",
                        help_text="Stable identifier (e.g., 'US-VA', 'RUS', 'DAK-TER')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Administrative Unit",
                "verbose_name_plural": "Administrative Units",
                "db_table": "AdministrativeUnits",
            },
        ),
        migrations.CreateModel(
            name="AdministrativeUnitIdentity",
            fields=[
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedDate"),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_column="ModifiedDate"),
                ),
                (
                    "administrative_unit_identity_id",
                    models.AutoField(
                        db_column="AdministrativeUnitIdentityID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "effective_from_date",
                    models.DateField(db_column="EffectiveFromDate"),
                ),
                (
                    "effective_to_date",
                    models.DateField(
                        blank=True, db_column="EffectiveToDate", null=True
                    ),
                ),
                ("unit_name", models.CharField(db_column="UnitName", max_length=255)),
                (
                    "unit_abbreviation",
                    models.CharField(db_column="UnitAbbreviation", max_length=10),
                ),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("COUNTRY", "Country"),
                            ("STATE", "State"),
                            ("PROVINCE", "Province"),
                            ("TERRITORY", "Territory"),
                            ("PREFECTURE", "Prefecture"),
                            ("COUNTY", "County"),
                            ("DISTRICT", "District"),
                            ("MUNICIPALITY", "Municipality"),
                        ],
                        db_column="UnitType",
                        max_length=20,
                    ),
                ),
                (
                    "hierarchy_level",
                    models.IntegerField(
                        db_column="HierarchyLevel",
                        help_text="1=Country, 2=State, 3=County, etc",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        choices=[
                            ("INITIAL", "Initial Creation"),
                            ("RENAMED", "Renamed"),
                            ("SPLIT", "Split"),
                            ("MERGED", "Merged"),
                            ("REORGANIZED", "Reorganized"),
                            ("INDEPENDENCE", "Gained Independence"),
                            ("ANNEXED", "Annexed"),
                            ("DISSOLVED", "Dissolved"),
                        ],
                        db_column="ChangeReason",
                        max_length=20,
                    ),
                ),
                (
                    "administrative_unit",
                    models.ForeignKey(
                        db_column="AdministrativeUnitID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identities",
                        to="common.administrativeunit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_administrative_unit",
                    models.ForeignKey(
                        blank=True,
                        db_column="ParentAdministrativeUnitID",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="child_identities",
                        to="common.administrativeunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Administrative Unit Identity",
                "verbose_name_plural": "Administrative Unit Identities",
                "db_table": "AdministrativeUnitIdentities",
                "ordering": ["administrative_unit", "-effective_from_date"],
            },
        ),
        migrations.CreateModel(
            name="AdministrativeUnitResponsibility",
            fields=[
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedDate"),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_column="ModifiedDate"),
                ),
                (
                    "administrative_unit_responsibility_id",
                    models.AutoField(
                        db_column="AdministrativeUnitResponsibilityID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_column="IsActive",
                        default=True,
                        help_text="Whether this responsibility is currently active",
                    ),
                ),
                ("notes", models.TextField(blank=True, db_column="Notes")),
                (
                    "administrative_unit",
                    models.ForeignKey(
                        db_column="AdministrativeUnitID",
                        help_text="The administrative unit this group is responsible for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsibilities",
                        to="common.administrativeunit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        db_column="GroupID",
                        help_text="The Django group responsible for this region",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="administrative_responsibilities",
                        to="auth.group",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Administrative Unit Responsibility",
                "verbose_name_plural": "Administrative Unit Responsibilities",
                "db_table": "AdministrativeUnitResponsibilities",
            },
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedDate"),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_column="ModifiedDate"),
                ),
                (
                    "color_id",
                    models.AutoField(
                        db_column="ColorID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "color_name",
                    models.CharField(db_column="ColorName", max_length=50, unique=True),
                ),
                (
                    "color_value",
                    colorfield.fields.ColorField(
                        db_column="ColorValue",
                        default="#FFFFFF",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Color",
                "verbose_name_plural": "Colors",
                "db_table": "Colors",
                "ordering": ["color_name"],
            },
        ),
        migrations.CreateModel(
            name="DateFormat",
            fields=[
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedDate"),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_column="ModifiedDate"),
                ),
                (
                    "date_format_id",
                    models.AutoField(
                        db_column="DateFormatID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "format_name",
                    models.CharField(
                        db_column="FormatName", max_length=100, unique=True
                    ),
                ),
                (
                    "format_description",
                    models.TextField(blank=True, db_column="FormatDescription"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Date Format",
                "verbose_name_plural": "Date Formats",
                "db_table": "DateFormats",
                "ordering": ["format_name"],
            },
        ),
        migrations.CreateModel(
            name="FramingStyle",
            fields=[
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedDate"),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_column="ModifiedDate"),
                ),
                (
                    "framing_style_id",
                    models.AutoField(
                        db_column="FramingStyleID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "framing_style_name",
                    models.CharField(
                        db_column="FramingStyleName", max_length=100, unique=True
                    ),
                ),
                (
                    "framing_description",
                    models.TextField(blank=True, db_column="FramingDescription"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Framing Style",
                "verbose_name_plural": "Framing Styles",
                "db_table": "FramingStyles",
                "ordering": ["framing_style_name"],
            },
        ),
        migrations.CreateModel(
            name="LetteringStyle",
            fields=[
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedDate"),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_column="ModifiedDate"),
                ),
                (
                    "lettering_style_id",
                    models.AutoField(
                        db_column="LetteringStyleID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "lettering_style_name",
                    models.CharField(
                        db_column="LetteringStyleName", max_length=100, unique=True
                    ),
                ),
                (
                    "lettering_description",
                    models.TextField(blank=True, db_column="LetteringDescription"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lettering Style",
                "verbose_name_plural": "Lettering Styles",
                "db_table": "LetteringStyles",
                "ordering": ["lettering_style_name"],
            },
        ),
        migrations.CreateModel(
            name="PostalFacility",
            fields=[
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedDate"),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_column="ModifiedDate"),
                ),
                (
                    "postal_facility_id",
                    models.AutoField(
                        db_column="PostalFacilityID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(
                        db_column="ReferenceCode",
                        help_text="Stable identifier (e.g., 'US-VA-RICHMOND-001', 'TR-IST-001')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        db_column="Latitude",
                        decimal_places=7,
                        help_text="Primary coordinates - if facility moved, use PostalFacilityIdentity override",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        db_column="Longitude",
                        decimal_places=7,
                        help_text="Primary coordinates - if facility moved, use PostalFacilityIdentity override",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Postal Facility",
                "verbose_name_plural": "Postal Facilities",
                "db_table": "PostalFacilities",
            },
        ),
        migrations.CreateModel(
            name="PostalFacilityIdentity",
            fields=[
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedDate"),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_column="ModifiedDate"),
                ),
                (
                    "postal_facility_identity_id",
                    models.AutoField(
                        db_column="PostalFacilityIdentityID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "effective_from_date",
                    models.DateField(db_column="EffectiveFromDate"),
                ),
                (
                    "effective_to_date",
                    models.DateField(
                        blank=True, db_column="EffectiveToDate", null=True
                    ),
                ),
                (
                    "facility_name",
                    models.CharField(
                        db_column="FacilityName",
                        help_text="Name as it appeared on postmarks",
                        max_length=255,
                    ),
                ),
                (
                    "facility_type",
                    models.CharField(
                        choices=[
                            ("POST_OFFICE", "Post Office"),
                            ("BRANCH", "Branch Office"),
                            ("STATION", "Station"),
                            ("SUB_STATION", "Sub-Station"),
                            ("CONTRACT_STATION", "Contract Station"),
                            ("RURAL_ROUTE", "Rural Route"),
                            ("DISCONTINUED", "Discontinued"),
                        ],
                        db_column="FacilityType",
                        max_length=50,
                    ),
                ),
                (
                    "is_operational",
                    models.BooleanField(db_column="IsOperational", default=True),
                ),
                (
                    "discontinuation_reason",
                    models.CharField(
                        blank=True, db_column="DiscontinuationReason", max_length=100
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        db_column="Latitude",
                        decimal_places=7,
                        help_text="Override location if facility moved during this period",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        db_column="Longitude",
                        decimal_places=7,
                        help_text="Override location if facility moved during this period",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, db_column="Notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "postal_facility",
                    models.ForeignKey(
                        db_column="PostalFacilityID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="identities",
                        to="common.postalfacility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Postal Facility Identity",
                "verbose_name_plural": "Postal Facility Identities",
                "db_table": "PostalFacilityIdentities",
                "ordering": ["postal_facility", "effective_from_date"],
            },
        ),
        migrations.CreateModel(
            name="JurisdictionalAffiliation",
            fields=[
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedDate"),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_column="ModifiedDate"),
                ),
                (
                    "jurisdictional_affiliation_id",
                    models.AutoField(
                        db_column="JurisdictionalAffiliationID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "effective_from_date",
                    models.DateField(db_column="EffectiveFromDate"),
                ),
                (
                    "effective_to_date",
                    models.DateField(
                        blank=True, db_column="EffectiveToDate", null=True
                    ),
                ),
                (
                    "affiliation_source",
                    models.CharField(
                        db_column="AffiliationSource",
                        help_text="Treaty, Organic Act, Congressional Act, etc.",
                        max_length=255,
                    ),
                ),
                (
                    "administrative_unit",
                    models.ForeignKey(
                        db_column="AdministrativeUnitID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="governed_facilities",
                        to="common.administrativeunit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "postal_facility_identity",
                    models.ForeignKey(
                        db_column="PostalFacilityIdentityID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jurisdictions",
                        to="common.postalfacilityidentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jurisdictional Affiliation",
                "verbose_name_plural": "Jurisdictional Affiliations",
                "db_table": "JurisdictionalAffiliations",
            },
        ),
        migrations.CreateModel(
            name="Postcover",
            fields=[
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedDate"),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_column="ModifiedDate"),
                ),
                (
                    "postcover_id",
                    models.AutoField(
                        db_column="PostcoverID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "postcover_key",
                    models.CharField(
                        db_column="PostcoverKey", max_length=100, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True, db_column="Description")),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        db_column="OwnerUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postcovers_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Postcover",
                "verbose_name_plural": "Postcovers",
                "db_table": "Postcovers",
            },
        ),
        migrations.CreateModel(
            name="PostcoverImage",
            fields=[
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedDate"),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_column="ModifiedDate"),
                ),
                (
                    "postcover_image_id",
                    models.AutoField(
                        db_column="PostcoverImageID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(db_column="OriginalFileName", max_length=255),
                ),
                (
                    "storage_filename",
                    models.CharField(
                        db_column="StorageFileName", max_length=255, unique=True
                    ),
                ),
                (
                    "file_checksum",
                    models.CharField(db_column="FileChecksum", max_length=64),
                ),
                ("mime_type", models.CharField(db_column="MimeType", max_length=50)),
                ("image_width", models.IntegerField(db_column="ImageWidth")),
                ("image_height", models.IntegerField(db_column="ImageHeight")),
                ("file_size_bytes", models.BigIntegerField(db_column="FileSizeBytes")),
                (
                    "image_view",
                    models.CharField(
                        choices=[
                            ("FRONT", "Front"),
                            ("BACK", "Back"),
                            ("INTERIOR", "Interior"),
                            ("DETAIL", "Detail"),
                        ],
                        db_column="ImageView",
                        max_length=20,
                    ),
                ),
                (
                    "image_description",
                    models.TextField(blank=True, db_column="ImageDescription"),
                ),
                (
                    "display_order",
                    models.IntegerField(db_column="DisplayOrder", default=0),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "postcover",
                    models.ForeignKey(
                        db_column="PostcoverID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="common.postcover",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        db_column="UploadedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postcover_images_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Postcover Image",
                "verbose_name_plural": "Postcover Images",
                "db_table": "PostcoverImages",
                "ordering": ["postcover", "display_order"],
            },
        ),
        migrations.CreateModel(
            name="Postmark",
            fields=[
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedDate"),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_column="ModifiedDate"),
                ),
                (
                    "postmark_id",
                    models.AutoField(
                        db_column="PostmarkID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "postmark_key",
                    models.CharField(
                        db_column="PostmarkKey", max_length=100, unique=True
                    ),
                ),
                (
                    "rate_location",
                    models.CharField(
                        choices=[
                            ("TOP", "Top"),
                            ("BOTTOM", "Bottom"),
                            ("LEFT", "Left"),
                            ("RIGHT", "Right"),
                            ("CENTER", "Center"),
                            ("NONE", "None"),
                        ],
                        db_column="RateLocation",
                        max_length=10,
                    ),
                ),
                (
                    "rate_value",
                    models.CharField(
                        db_column="RateValue",
                        help_text="5c, 10c, Free, Paid, etc",
                        max_length=50,
                    ),
                ),
                (
                    "is_manuscript",
                    models.BooleanField(
                        db_column="IsManuscript",
                        default=False,
                        help_text="Hand-written or hand-stamped vs printed",
                    ),
                ),
                (
                    "other_characteristics",
                    models.TextField(blank=True, db_column="OtherCharacteristics"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "date_format",
                    models.ForeignKey(
                        db_column="DateFormatID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postmarks",
                        to="common.dateformat",
                    ),
                ),
                (
                    "framing_style",
                    models.ForeignKey(
                        db_column="FramingStyleID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postmarks",
                        to="common.framingstyle",
                    ),
                ),
                (
                    "lettering_style",
                    models.ForeignKey(
                        db_column="LetteringStyleID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postmarks",
                        to="common.letteringstyle",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "postal_facility_identity",
                    models.ForeignKey(
                        db_column="PostalFacilityIdentityID",
                        help_text="The facility identity when this postmark was used",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postmarks",
                        to="common.postalfacilityidentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Postmark",
                "verbose_name_plural": "Postmarks",
                "db_table": "Postmarks",
            },
        ),
        migrations.CreateModel(
            name="PostcoverPostmark",
            fields=[
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedDate"),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_column="ModifiedDate"),
                ),
                (
                    "postcover_postmark_id",
                    models.AutoField(
                        db_column="PostcoverPostmarkID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position_order", models.IntegerField(db_column="PositionOrder")),
                (
                    "postmark_location",
                    models.CharField(
                        choices=[
                            ("FRONT", "Front"),
                            ("BACK", "Back"),
                            ("FRONT_UPPER_RIGHT", "Front Upper Right"),
                            ("FRONT_UPPER_LEFT", "Front Upper Left"),
                            ("BACK_UPPER_RIGHT", "Back Upper Right"),
                            ("BACK_UPPER_LEFT", "Back Upper Left"),
                            ("BACK_LOWER_LEFT", "Back Lower Left"),
                            ("BACK_LOWER_RIGHT", "Back Lower Right"),
                        ],
                        db_column="PostmarkLocation",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "postcover",
                    models.ForeignKey(
                        db_column="PostcoverID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postcover_postmarks",
                        to="common.postcover",
                    ),
                ),
                (
                    "postmark",
                    models.ForeignKey(
                        db_column="PostmarkID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postcover_postmarks",
                        to="common.postmark",
                    ),
                ),
            ],
            options={
                "verbose_name": "Postcover Postmark",
                "verbose_name_plural": "Postcover Postmarks",
                "db_table": "PostcoverPostmarks",
                "ordering": ["postcover", "position_order"],
            },
        ),
        migrations.CreateModel(
            name="PostmarkColor",
            fields=[
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedDate"),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_column="ModifiedDate"),
                ),
                (
                    "postmark_color_id",
                    models.AutoField(
                        db_column="PostmarkColorID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        db_column="ColorID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postmark_colors",
                        to="common.color",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "postmark",
                    models.ForeignKey(
                        db_column="PostmarkID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postmark_colors",
                        to="common.postmark",
                    ),
                ),
            ],
            options={
                "verbose_name": "Postmark Color",
                "verbose_name_plural": "Postmark Colors",
                "db_table": "PostmarkColors",
            },
        ),
        migrations.CreateModel(
            name="PostmarkDatesSeen",
            fields=[
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedDate"),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_column="ModifiedDate"),
                ),
                (
                    "postmark_dates_seen_id",
                    models.AutoField(
                        db_column="PostmarkDatesSeenID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("earliest_date_seen", models.DateField(db_column="EarliestDateSeen")),
                ("latest_date_seen", models.DateField(db_column="LatestDateSeen")),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "postmark",
                    models.ForeignKey(
                        db_column="PostmarkID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dates_seen",
                        to="common.postmark",
                    ),
                ),
            ],
            options={
                "verbose_name": "Postmark Dates Seen",
                "verbose_name_plural": "Postmark Dates Seen",
                "db_table": "PostmarkDatesSeen",
                "ordering": ["earliest_date_seen"],
            },
        ),
        migrations.CreateModel(
            name="PostmarkImage",
            fields=[
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedDate"),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_column="ModifiedDate"),
                ),
                (
                    "postmark_image_id",
                    models.AutoField(
                        db_column="PostmarkImageID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(db_column="OriginalFileName", max_length=255),
                ),
                (
                    "storage_filename",
                    models.CharField(
                        db_column="StorageFileName", max_length=255, unique=True
                    ),
                ),
                (
                    "file_checksum",
                    models.CharField(db_column="FileChecksum", max_length=64),
                ),
                ("mime_type", models.CharField(db_column="MimeType", max_length=50)),
                ("image_width", models.IntegerField(db_column="ImageWidth")),
                ("image_height", models.IntegerField(db_column="ImageHeight")),
                ("file_size_bytes", models.BigIntegerField(db_column="FileSizeBytes")),
                (
                    "image_view",
                    models.CharField(
                        choices=[
                            ("FULL", "Full"),
                            ("DETAIL", "Detail"),
                            ("COMPARISON", "Comparison"),
                        ],
                        db_column="ImageView",
                        max_length=20,
                    ),
                ),
                (
                    "image_description",
                    models.TextField(blank=True, db_column="ImageDescription"),
                ),
                (
                    "display_order",
                    models.IntegerField(db_column="DisplayOrder", default=0),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "postmark",
                    models.ForeignKey(
                        db_column="PostmarkID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="common.postmark",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        db_column="UploadedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postmark_images_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Postmark Image",
                "verbose_name_plural": "Postmark Images",
                "db_table": "PostmarkImages",
                "ordering": ["postmark", "display_order"],
            },
        ),
        migrations.CreateModel(
            name="PostmarkPublication",
            fields=[
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedDate"),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_column="ModifiedDate"),
                ),
                (
                    "postmark_publication_id",
                    models.AutoField(
                        db_column="PostmarkPublicationID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "publication_title",
                    models.CharField(db_column="PublicationTitle", max_length=500),
                ),
                ("author", models.CharField(db_column="Author", max_length=255)),
                ("publisher", models.CharField(db_column="Publisher", max_length=255)),
                ("publication_date", models.DateField(db_column="PublicationDate")),
                ("isbn", models.CharField(blank=True, db_column="ISBN", max_length=20)),
                (
                    "edition",
                    models.CharField(blank=True, db_column="Edition", max_length=50),
                ),
                (
                    "publication_type",
                    models.CharField(
                        choices=[
                            ("BOOK", "Book"),
                            ("CATALOG", "Catalog"),
                            ("JOURNAL", "Journal"),
                            ("WEBSITE", "Website"),
                            ("NEWSLETTER", "Newsletter"),
                        ],
                        db_column="PublicationType",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Postmark Publication",
                "verbose_name_plural": "Postmark Publications",
                "db_table": "PostmarkPublications",
                "ordering": ["-publication_date"],
            },
        ),
        migrations.CreateModel(
            name="PostmarkPublicationReference",
            fields=[
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedDate"),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_column="ModifiedDate"),
                ),
                (
                    "postmark_publication_reference_id",
                    models.AutoField(
                        db_column="PostmarkPublicationReferenceID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "published_id",
                    models.CharField(db_column="PublishedID", max_length=100),
                ),
                (
                    "reference_location",
                    models.CharField(db_column="ReferenceLocation", max_length=255),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "postmark",
                    models.ForeignKey(
                        db_column="PostmarkID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publication_references",
                        to="common.postmark",
                    ),
                ),
                (
                    "postmark_publication",
                    models.ForeignKey(
                        db_column="PostmarkPublicationID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postmark_references",
                        to="common.postmarkpublication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Postmark Publication Reference",
                "verbose_name_plural": "Postmark Publication References",
                "db_table": "PostmarkPublicationReferences",
            },
        ),
        migrations.CreateModel(
            name="PostmarkShape",
            fields=[
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedDate"),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_column="ModifiedDate"),
                ),
                (
                    "postmark_shape_id",
                    models.AutoField(
                        db_column="PostmarkShapeID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "shape_name",
                    models.CharField(
                        db_column="ShapeName", max_length=100, unique=True
                    ),
                ),
                (
                    "shape_description",
                    models.TextField(blank=True, db_column="ShapeDescription"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Postmark Shape",
                "verbose_name_plural": "Postmark Shapes",
                "db_table": "PostmarkShapes",
                "ordering": ["shape_name"],
            },
        ),
        migrations.AddField(
            model_name="postmark",
            name="postmark_shape",
            field=models.ForeignKey(
                db_column="PostmarkShapeID",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="postmarks",
                to="common.postmarkshape",
            ),
        ),
        migrations.CreateModel(
            name="PostmarkSize",
            fields=[
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedDate"),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_column="ModifiedDate"),
                ),
                (
                    "postmark_size_id",
                    models.AutoField(
                        db_column="PostmarkSizeID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        db_column="Width", decimal_places=2, max_digits=8
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        db_column="Height", decimal_places=2, max_digits=8
                    ),
                ),
                (
                    "size_notes",
                    models.CharField(blank=True, db_column="SizeNotes", max_length=255),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "postmark",
                    models.ForeignKey(
                        db_column="PostmarkID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="common.postmark",
                    ),
                ),
            ],
            options={
                "verbose_name": "Postmark Size",
                "verbose_name_plural": "Postmark Sizes",
                "db_table": "PostmarkSizes",
            },
        ),
        migrations.CreateModel(
            name="PostmarkValuation",
            fields=[
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedDate"),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_column="ModifiedDate"),
                ),
                (
                    "postmark_valuation_id",
                    models.AutoField(
                        db_column="PostmarkValuationID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "estimated_value",
                    models.DecimalField(
                        db_column="EstimatedValue", decimal_places=2, max_digits=10
                    ),
                ),
                ("valuation_date", models.DateField(db_column="ValuationDate")),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "postmark",
                    models.ForeignKey(
                        db_column="PostmarkID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valuations",
                        to="common.postmark",
                    ),
                ),
                (
                    "valued_by_user",
                    models.ForeignKey(
                        db_column="ValuedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postmark_valuations_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Postmark Valuation",
                "verbose_name_plural": "Postmark Valuations",
                "db_table": "PostmarkValuations",
                "ordering": ["-valuation_date"],
            },
        ),
        migrations.AddIndex(
            model_name="administrativeunit",
            index=models.Index(
                fields=["reference_code"], name="Administrat_Referen_6ae8de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="administrativeunitidentity",
            index=models.Index(
                fields=["administrative_unit", "effective_from_date"],
                name="Administrat_Adminis_d52927_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="administrativeunitidentity",
            index=models.Index(
                fields=["effective_from_date", "effective_to_date"],
                name="Administrat_Effecti_800b64_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="administrativeunitresponsibility",
            index=models.Index(
                fields=["administrative_unit", "is_active"],
                name="Administrat_Adminis_430d8b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="administrativeunitresponsibility",
            index=models.Index(
                fields=["group", "is_active"], name="Administrat_GroupID_f85c24_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="administrativeunitresponsibility",
            unique_together={("administrative_unit", "group")},
        ),
        migrations.AddIndex(
            model_name="postalfacility",
            index=models.Index(
                fields=["reference_code"], name="PostalFacil_Referen_277c71_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postalfacilityidentity",
            index=models.Index(
                fields=["facility_name", "effective_from_date"],
                name="PostalFacil_Facilit_99565d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="postalfacilityidentity",
            index=models.Index(
                fields=["postal_facility", "effective_from_date"],
                name="PostalFacil_PostalF_9c54f6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="jurisdictionalaffiliation",
            index=models.Index(
                fields=["postal_facility_identity", "effective_from_date"],
                name="Jurisdictio_PostalF_8215d9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="jurisdictionalaffiliation",
            index=models.Index(
                fields=["administrative_unit", "effective_from_date"],
                name="Jurisdictio_Adminis_5035af_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="postcover",
            index=models.Index(
                fields=["owner_user"], name="Postcovers_OwnerUs_3a89ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postcover",
            index=models.Index(
                fields=["postcover_key"], name="Postcovers_Postcov_a79a74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postcoverimage",
            index=models.Index(
                fields=["postcover", "display_order"],
                name="PostcoverIm_Postcov_cb9bda_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="postcoverimage",
            index=models.Index(
                fields=["file_checksum"], name="PostcoverIm_FileChe_1473bb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="postcoverpostmark",
            unique_together={("postcover", "postmark", "position_order")},
        ),
        migrations.AlterUniqueTogether(
            name="postmarkcolor",
            unique_together={("postmark", "color")},
        ),
        migrations.AddIndex(
            model_name="postmarkimage",
            index=models.Index(
                fields=["postmark", "display_order"],
                name="PostmarkIma_Postmar_a95f9e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="postmarkimage",
            index=models.Index(
                fields=["file_checksum"], name="PostmarkIma_FileChe_1d7426_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="postmarkpublicationreference",
            unique_together={("postmark", "postmark_publication", "published_id")},
        ),
        migrations.AddIndex(
            model_name="postmark",
            index=models.Index(
                fields=["postal_facility_identity"], name="Postmarks_PostalF_b9397c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postmark",
            index=models.Index(
                fields=["postmark_key"], name="Postmarks_Postmar_c85d2f_idx"
            ),
        ),
    ]
